LAB NUMPY

In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)
# hint: import … as`

import numpy as np

In [6]:

#### 2. Create a null vector of size 10 (★☆☆)
#hint: np.zeros`

np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#hint: array[4]`

a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#hint: arange`
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [32]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#hint: reshape`
grid = np.arange(0, 9).reshape((3, 3)) 
print(grid)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#hint: np.nonzero`
c = np.nonzero([1,2,0,0,4,0])
pint(c)

(array([0, 1, 4]),)

In [59]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#hint: np.eye`

d = np.eye(3,3)
print(d)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
#8Create a 3x3x3 array with random values (★☆☆)
#hint: np.random.random`

e = np.random.random((3,3,3))
print(e)


[[[0.71527138 0.30781284 0.68003877]
  [0.53416843 0.83913554 0.80946762]
  [0.45999501 0.35324058 0.81176079]]

 [[0.55879565 0.13885906 0.75842373]
  [0.63516221 0.90759907 0.91968723]
  [0.47428768 0.6679349  0.73275457]]

 [[0.85191493 0.72180575 0.81574366]
  [0.92376706 0.78764066 0.5566482 ]
  [0.16141573 0.64404683 0.04072391]]]


In [63]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#hint: min, max`

X = np.random.random(10)

print(min(X))
print(max(X))

0.0050355345151780195
0.8621519718030519


In [64]:
#10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`

x = np.random.random(30)

y = x.mean()
print(y)


0.5185682994162549


In [81]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#hint: np.diag`
x = np.zeros((5,5))([1,2,3,4])
y = n.diag(x)

print(y)


TypeError: 'numpy.ndarray' object is not callable

In [87]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#hint: (x -mean)/std`

x = np.random.normal(0, 1, (5, 5))
print(x)

[[ 0.0981816  -0.27978707  0.448196    0.72105132  0.83482612]
 [-0.07976215 -1.68515142 -0.30111737 -0.32377182 -1.72518007]
 [-0.18033127 -0.58571132  0.14114028 -1.45286355  1.12712755]
 [ 1.82321708  0.52137516  2.24224058 -1.30330824 -0.93420466]
 [ 0.25679386  1.16975525  0.85876033  0.05944269  0.10393673]]


In [70]:
#### 13. How to find common values between two arrays? (★☆☆)
#hint: np.intersect1d`

x = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)
print(np.intersect1d(x,y))

[2 5 8 9]


In [73]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#hint: sort`

x = np.random.random(10)

sorted(x)

[0.03288398059476205,
 0.06425342576542026,
 0.17193033139476133,
 0.19343937834164848,
 0.46654781532573464,
 0.6635146138594541,
 0.6671551751951527,
 0.8434569184634921,
 0.8682714962757396,
 0.9840298608397627]

In [85]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#hint: argmax`

x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.18208839 0.86228518 0.81873748 0.0238843  0.32810812 0.71656061
 0.27998589 0.46844662 0.         0.03481   ]


In [ ]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)`

In [84]:
#### 17. How to get the n largest values of an array (★★★)
x = np.arange(10000)
np.random.shuffle(x)
n = 5
print (x[np.argsort(x)[-n:]])

In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#hint: np.where`